model_selection:
  logistic_regression:
    penalty: ["l2"]
    C: [0.1, 1, 10]
    solver: ["lbfgs", "liblinear"]
    max_iter: [300,500, 1000]

  xgboost:
    n_estimators: [50, 100, 200]
    learning_rate: [0.01, 0.1, 0.2]
    max_depth: [3, 5, 7]
    subsample: [0.8, 1.0]
    colsample_bytree: [0.8, 1.0]

scaling:
  method: standard 

split:
  test_size: 0.2
  random_state: 42

target_column: "class"
